name: Docker Image CI for GHCR

on:
  push:
    branches:
      - development
      - stage
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace variables
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{ github.workspace }}/API/appsettings.json'
        env:
          ConnectionStrings.Postgres: "Host=db.bvsilva.com;Port=15432;Database=forlogic;Username=forlogic_user;Password=forlogic_password"
          ConnectionStrings.Redis: "redis.bvsilva.com:16379"

      - name: Login to GitHub Container Registry
        run: |
          docker login --username ${{ github.actor }} --password ${{ secrets.GHCR_TOKEN }} ghcr.io
  
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./API/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

        
